

// This file is auto-generated from docs/backend.json
// Do not edit this file directly.

export type user_root = {
    schools?: { [key: string]: string };
    activeSchoolId?: string;
    isSuperAdmin?: boolean;
};

export type school = {
    name: string;
    drena?: string;
    status: "active" | "suspended" | "deleted";
    directorId: string;
    directorFirstName: string;
    directorLastName: string;
    schoolCode: string;
    deletedAt?: any;
    matricule?: string;
    cnpsEmployeur?: string;
    directorPhone?: string;
    directorEmail?: string;
    createdAt?: any;
    updatedAt?: any;
    address: string;
    phone: string;
    website: string;
    mainLogoUrl: string;
    digitalSignatureUrl?: string;
    email: string;
    isSetupComplete?: boolean;
    subscription?: {
        plan?: "Essentiel" | "Pro" | "Premium";
        status?: "active" | "trialing" | "past_due" | "canceled";
        startDate?: string;
        endDate?: string;
        maxStudents?: number;
        maxCycles?: number;
        activeModules?: ("sante" | "cantine" | "transport" | "internat" | "immobilier" | "activites" | "rh")[];
    };
    id?: string;
};

export type parent_profile = {
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    isPrimary?: boolean;
};

export type parent_session = {
    schoolId?: string;
    studentIds?: string[];
    accessCode?: string;
    isActive?: boolean;
    createdAt?: string;
    expiresAt?: string;
};

export type contact_request = {
    firstName: string;
    lastName: string;
    email: string;
    schoolName: string;
    phone?: string;
    schoolType?: string;
    studentCount?: string;
    needs?: string[];
    message?: string;
    meetingDate?: string;
    meetingTime?: string;
    newsletter?: boolean;
    submittedAt?: string;
};

export type survey_response = {
    schoolName: string;
    schoolType: string;
    studentCount: string;
    currentManagement: string;
    painPoints: string[];
    featureInterest: {
        pedagogy?: number;
        finance?: number;
        communication?: number;
        schoolLife?: number;
        rh?: number;
        infra?: number;
    };
    submittedAt: string;
    budget?: string;
    comments?: string;
    contactEmail?: string;
};

export type support_ticket = {
    userId: string;
    schoolId: string;
    subject: string;
    category: string;
    description: string;
    status: "open" | "in_progress" | "closed";
    submittedAt?: string;
    closedAt?: string;
    userDisplayName?: string;
    userEmail?: string;
};

export type system_log = {
    adminId?: string;
    action?: string;
    target?: string;
    details?: any;
    ipAddress?: string;
    userAgent?: string;
    timestamp?: string;
};

export type system_setting = {
    maintenanceMode?: boolean;
    registrationEnabled?: boolean;
    defaultSchoolPlan?: string;
    smtpSettings?: any;
    storageQuota?: number;
    backupFrequency?: string;
    apiRateLimit?: number;
    supportWhatsApp?: string;
};

export type admin_role = {
    schoolId: string;
    name: string;
    permissions: {
        manageUsers?: boolean;
        viewUsers?: boolean;
        manageSchools?: boolean;
        viewSchools?: boolean;
        manageClasses?: boolean;
        manageGrades?: boolean;
        viewGrades?: boolean;
        manageDiscipline?: boolean;
        manageSystem?: boolean;
        viewAnalytics?: boolean;
        manageSettings?: boolean;
        manageBilling?: boolean;
        manageCommunication?: boolean;
        manageSchedule?: boolean;
        manageAttendance?: boolean;
        manageLibrary?: boolean;
        manageCantine?: boolean;
        manageTransport?: boolean;
        manageInternat?: boolean;
        manageInventory?: boolean;
        manageRooms?: boolean;
        manageActivities?: boolean;
        manageMedical?: boolean;
        viewSupportTickets?: boolean;
        manageSupportTickets?: boolean;
        apiAccess?: boolean;
        exportData?: boolean;
    };
    description?: string;
    isSystem?: boolean;
};

export type staff = {
    uid: string;
    email: string;
    schoolId: string;
    role: "directeur" | "directeur_pedagogique" | "secretaire" | "enseignant" | "enseignant_principal" | "comptable" | "bibliothecaire" | "surveillant" | "infirmier" | "personnel" | "chauffeur" | "accompagnateur";
    firstName: string;
    lastName: string;
    hireDate: string;
    baseSalary: number;
    contractType?: 'Titulaire' | 'Vacataire';
    hourlyRate?: number;
    baseHours?: number; // Heures effectuées pour le mois en cours
    displayName?: string;
    photoURL?: string;
    isAdmin?: boolean;
    adminRole?: string;
    phone?: string;
    matricule?: string;
    status?: "Actif" | "Inactif";
    subject?: string;
    classId?: string;
    situationMatrimoniale?: "Célibataire" | "Marié(e)" | "Divorcé(e)" | "Veuf(ve)";
    enfants?: number;
    categorie?: string;
    cnpsEmploye?: string;
    indemniteTransportImposable?: number;
    indemniteResponsabilite?: number;
    indemniteLogement?: number;
    indemniteSujetion?: number;
    indemniteCommunication?: number;
    indemniteRepresentation?: number;
    transportNonImposable?: number;
    banque?: string;
    numeroCompte?: string;
    CB?: string;
    CG?: string;
    Cle_RIB?: string;
    CNPS?: boolean;
};

export type staff_leave = {
    staffId: string;
    staffName: string;
    schoolId: string;
    startDate: string;
    endDate: string;
    type: "Congé Annuel" | "Congé Maladie" | "Congé Maternité/Paternité" | "Permission Spéciale" | "Absence Non Justifiée";
    reason: string;
    status: "En attente" | "Approuvé" | "Rejeté";
    requestedAt: any;
    reviewedBy?: string;
    reviewDate?: string;
};

export type parent = {
    uid: string;
    email: string;
    schoolId: string;
    studentIds: string[];
    displayName?: string;
    photoURL?: string;
};

export type student = {
    schoolId: string;
    matricule: string;
    firstName: string;
    lastName: string;
    status: "Actif" | "En attente" | "Transféré" | "Diplômé" | "Radié";
    dateOfBirth: string;
    placeOfBirth: string;
    gender: "Masculin" | "Féminin";
    parent1FirstName: string;
    parent1LastName: string;
    parent1Contact: string;
    parent1Email?: string;
    tuitionFee: number;
    amountDue: number;
    tuitionStatus: "Soldé" | "En retard" | "Partiel";
    photoURL?: string;
    classId?: string;
    class?: string;
    cycle?: string;
    grade?: string;
    address?: string;
    parent2FirstName?: string;
    parent2LastName?: string;
    parent2Contact?: string;
    parent2Email?: string;
    parentIds?: string[];
    previousSchool?: string;
    discountAmount?: number;
    discountReason?: string;
    feedback?: string;
    createdAt?: string;
    updatedAt?: any;
    createdBy?: string;
    updatedBy?: string;
    inscriptionYear?: number;
    id?: string;
};

export type discipline_incident = {
    studentId: string;
    schoolId: string;
    studentName: string;
    classId: string;
    date: string;
    type: "Avertissement Oral" | "Avertissement Écrit" | "Retenue" | "Mise à pied" | "Exclusion temporaire" | "Exclusion définitive";
    reason: string;
    reportedById: string;
    reportedByName?: string;
    actionsTaken?: string;
    parentNotified?: boolean;
    followUpNotes?: string;
};

export type cycle = {
    schoolId: string;
    name: string;
    code: string;
    order: number;
    isActive?: boolean;
    description?: string;
    ageRange?: {
        min?: number;
        max?: number;
    };
    createdAt?: string;
    updatedAt?: string;
    color?: string;
};

export type niveau = {
    schoolId: string;
    cycleId: string;
    name: string;
    code: string;
    order: number;
    ageMin: number;
    ageMax: number;
    capacity: number;
    ageRange?: any;
    color?: string;
    description?: string;
    createdAt?: string;
    updatedAt?: string;
    id?: string;
};

export type class_type = {
    schoolId: string;
    cycleId: string;
    niveauId: string;
    name: string;
    code: string;
    academicYear: string;
    studentCount: number;
    maxStudents: number;
    status: "active" | "inactive" | "archived";
    isFull: boolean;
    createdBy: string;
    grade?: string;
    section?: string;
    mainTeacherId?: string;
    mainTeacherName?: string;
    teacherIds?: string[];
    coordinatorId?: string;
    schedule?: {
        startTime?: string;
        endTime?: string;
        days?: string[];
    };
    classroom?: string;
    building?: string;
    createdAt?: string;
    updatedAt?: string;
    id?: string;
};

export type studentClassAssignment = {
    schoolId: string;
    studentId: string;
    classeId: string;
    academicYear: string;
    startDate: string;
    promotionType: "normal" | "redoublement" | "avancement";
    status: "active" | "transferred" | "graduated" | "withdrawn";
    createdBy: string;
    endDate?: string;
    previousClass?: string;
    notes?: string;
    createdAt?: string;
    className?: string;
    gradeName?: string;
    cycleName?: string;
};

export type timetableEntry = {
    schoolId: string;
    classId: string;
    teacherId: string;
    subject: string;
    day: "Lundi" | "Mardi" | "Mercredi" | "Jeudi" | "Vendredi" | "Samedi";
    startTime: string;
    endTime: string;
    classroom?: string;
    color?: string;
    id?: string;
};

export type gradeEntry = {
    schoolId: string;
    subject: string;
    type: "Interrogation" | "Devoir" | "Composition Mensuelle" | "Composition Nationale" | "Composition de Zone";
    date: string;
    grade: number;
    coefficient: number;
    id?: string;
};

export type accountingTransaction = {
    schoolId: string;
    date: string;
    description: string;
    category: string;
    type: "Revenu" | "Dépense";
    amount: number;
    studentId?: string;
};

export type payment = {
    schoolId: string;
    studentId: string;
    date: string;
    amount: number;
    description: string;
    accountingTransactionId: string;
    payerFirstName: string;
    payerLastName: string;
    method: "Espèces" | "Chèque" | "Virement Bancaire" | "Paiement Mobile";
    payerContact?: string;
    id?: string;
};

export type libraryBook = {
    schoolId: string;
    title: string;
    author: string;
    quantity: number;
    frontCoverUrl?: string;
    backCoverUrl?: string;
    createdAt?: string;
    id?: string;
};

export type libraryLoan = {
    bookId: string;
    studentId: string;
    borrowedDate: string;
    dueDate: string;
    status: "borrowed" | "returned" | "overdue";
    returnedDate?: string;
};

export type message = {
    schoolId: string;
    title: string;
    content: string;
    senderId: string;
    senderName: string;
    createdAt: any;
    recipients: {
        all?: boolean;
        teachers?: boolean;
        staff?: boolean;
        classes?: string[];
    };
    readBy?: string[];
};

export type notification = {
    userId: string;
    title: string;
    content: string;
    href: string;
    isRead: boolean;
    createdAt: string;
};

export type absence = {
    schoolId: string;
    studentId: string;
    studentName: string;
    classId?: string;
    date: string;
    type: "Journée entière" | "Matin" | "Après-midi";
    justified: boolean;
    recordedBy: string;
    reason?: string;
    id?: string;
};

export type fee = {
    schoolId: string;
    grade: string;
    amount: string;
    installments: string;
    details?: string;
    id?: string;
};

export type subject = {
    schoolId: string;
    name: string;
    code?: string;
    color?: string;
};

export type canteenMenu = {
    date: string;
    mealType: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    status: "draft" | "published" | "archived";
    categories: {
        name?: string;
        items?: {
            name?: string;
            description?: string;
            allergens?: string[];
            priceStudent?: number;
            priceStaff?: number;
            options?: string[];
        }[];
    }[];
    specialMenus?: {
        vegetarian?: {
            available?: boolean;
            mainCourse?: string;
        };
        halal?: {
            available?: boolean;
            mainCourse?: string;
        };
        allergies?: string[];
    };
    id?: string;
};

export type canteenReservation = {
    studentId: string;
    date: string;
    mealType: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    status: "pending" | "confirmed" | "cancelled" | "attended";
    paymentStatus: "unpaid" | "paid" | "partially_paid";
    price: number;
    menuChoice?: {
        entree?: string;
        mainCourse?: string;
        dessert?: string;
        option?: string;
    };
    specialRequirements?: string;
    paidAmount?: number;
    attendanceTime?: string;
    notes?: string;
};

export type canteenSubscription = {
    studentId: string;
    type: "ponctuel" | "hebdomadaire" | "mensuel" | "trimestriel" | "annuel";
    startDate: string;
    endDate: string;
    price: number;
    status: "active" | "inactive" | "expired";
    daysOfWeek?: string[];
    mealType?: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    autoRenew?: boolean;
    missedMeals?: number;
    remainingMeals?: number;
    id?: string;
};

export type canteenInventoryItem = {
    schoolId: string;
    name: string;
    category: "ingredient" | "boisson" | "fourniture" | "autre";
    quantity: number;
    unit: "kg" | "l" | "unité" | "paquet" | "sac";
    minThreshold: number;
    lastUpdated: string;
    pricePerUnit?: number;
    id?: string;
};

export type canteenInventoryLog = {
    itemId: string;
    type: "in" | "out";
    quantity: number;
    reason: "achat" | "consommation" | "perte" | "ajustement";
    timestamp: string;
    staffId: string;
    notes?: string;
};

export type canteenDailyStats = {
    date: string;
    mealsServed: {
        petit_dejeuner?: number;
        dejeuner?: number;
        gouter?: number;
        diner?: number;
    };
    revenue: number;
    totalReservations: number;
    lastUpdated: string;
};

export type bus = {
    registrationNumber: string;
    capacity: number;
    type: "standard" | "minibus" | "adapted";
    status: "active" | "maintenance" | "inactive";
    features?: string[];
    driverId?: string;
    monitorId?: string;
    lastMaintenance?: string;
    nextMaintenance?: string;
    insurance?: {
        company?: string;
        policyNumber?: string;
        expiryDate?: string;
    };
};

export type route = {
    name: string;
    busId: string;
    driverId?: string;
    schedule?: {
        morning?: routeSchedule;
        evening?: routeSchedule;
    };
    status?: "on_time" | "delayed" | "cancelled";
    currentLocation?: {
        lat?: number;
        lng?: number;
        timestamp?: string;
    };
};

export type routeSchedule = {
    startTime?: string;
    arrivalTime?: string;
    stops?: {
        stopId?: string;
        name?: string;
        address?: string;
        scheduledTime?: string;
        actualTime?: string;
        students?: string[];
    }[];
};

export type transportSubscription = {
    studentId: string;
    routeId: string;
    stopId: string;
    type: "aller_seul" | "retour_seul" | "aller_retour";
    period: "trimestriel" | "semestriel" | "annuel";
    price: number;
    status: "active" | "inactive";
    startDate: string;
    endDate: string;
    paymentStatus?: "unpaid" | "paid";
    id?: string;
};

export type building = {
    name: string;
    type: "garcons" | "filles" | "mixte" | "administratif" | "pedagogique" | "sportif" | "autre";
    capacity: number;
    responsableId?: string;
    status?: "active" | "maintenance" | "full";
    features?: string[];
};

export type room = {
    buildingId: string;
    number: string;
    capacity: number;
    status: "available" | "occupied" | "maintenance";
    monthlyRate: number;
};

export type occupant = {
    studentId: string;
    roomId: string;
    startDate: string;
    status: "active" | "pending" | "terminated" | "suspended";
    endDate?: string;
    nextPaymentDue?: string;
};

export type log = {
    studentId: string;
    type: "entree" | "sortie";
    timestamp: string;
    reason: string;
    status: "pending" | "authorized" | "returned" | "late" | "cancelled";
    authorizedBy?: string;
};

export type materiel = {
    name: string;
    category: "Mobilier" | "Informatique" | "Pédagogique" | "Sportif" | "Autre";
    quantity: number;
    status: "neuf" | "bon" | "à réparer" | "hors_service";
    locationId: string;
    acquisitionDate?: string;
    value?: number;
    photoURL?: string;
};

export type salle = {
    name: string;
    type: "salle_de_classe" | "salle_de_reunion" | "laboratoire" | "amphitheatre" | "gymnase";
    capacity: number;
    buildingId?: string;
    equipments?: string[];
};

export type reservation_salle = {
    salleId: string;
    reservedBy: string;
    eventName: string;
    startTime: string;
    endTime: string;
    status: "confirmée" | "en_attente" | "annulée";
    notes?: string;
};

export type tache_maintenance = {
    title: string;
    priority: "haute" | "moyenne" | "basse";
    status: "à_faire" | "en_cours" | "terminée";
    createdAt: string;
    assignedTo?: string;
    dueDate?: string;
    description?: string;
    location?: string;
};

export type key_trousseau = {
    name: string;
    status: "disponible" | "emprunté";
    description?: string;
    keys?: string[];
    lastHolderId?: string;
};

export type key_log = {
    trousseauId: string;
    staffId: string;
    type: "emprunt" | "retour";
    timestamp: string;
    notes?: string;
};

export type dossierMedical = {
    studentId: string;
    schoolId: string;
    groupeSanguin?: string;
    allergies?: string[];
    maladiesChroniques?: string[];
    urgences?: {
        contact1?: string;
        assurance?: string;
        numeroPolice?: string;
    };
};

export type vaccination = {
    schoolId: string;
    nom: string;
    date: string;
    rappel?: string;
};

export type consultation = {
    schoolId: string;
    date: string;
    motif: string;
    diagnostic: string;
    traitement?: string;
    medecin?: string;
};

export type activite = {
    name: string;
    type: "sportive" | "culturelle" | "club";
    teacherInChargeId: string;
    description?: string;
    schedule?: string;
};

export type inscriptionActivite = {
    studentId: string;
    activiteId: string;
    academicYear: string;
};

export type competition = {
    name: string;
    date: string;
    description?: string;
    results?: string;
};

export type participationCompetition = {
    studentId: string;
    competitionId: string;
    rank?: string;
    notes?: string;
};

export type payrollRun = {
    period: string;
    executionDate: string;
    totalMass: number;
    employeeCount: number;
    status: "Terminé" | "En cours" | "Annulé";
    processedBy: string;
    processedByName?: string;
};

export type payroll_payslip = {
    staffId: string;
    staffName: string;
    payslipDetails: any;
};


export interface UserProfile extends staff {
    permissions?: Partial<admin_role['permissions']>;
    isAdmin?: boolean;
    isSuperAdmin?: boolean;
}

export type classe = class_type;
export interface AppUser {
    uid: string;
    isParent: boolean;
    authUser: any; // Firebase User
    profile?: UserProfile;
    parentStudentIds?: string[];
    schoolId?: string | null;
    schools?: { [key: string]: string };
    schoolNames?: { [key: string]: string };
    displayName?: string | null;
    photoURL?: string | null;
    email?: string | null;
}
