
// This file is auto-generated from docs/backend.json
// Do not edit this file directly.

export type user_root = {
    schoolId: string;
};

export type school = {
    name: string;
    directorId: string;
    directorFirstName: string;
    directorLastName: string;
    schoolCode: string;
    matricule?: string;
    cnpsEmployeur?: string;
    directorPhone?: string;
    createdAt?: string;
    address?: string;
    phone?: string;
    website?: string;
    mainLogoUrl?: string;
    email?: string;
    subscription?: {
        plan?: "Essentiel" | "Pro" | "Premium";
        status?: "active" | "trialing" | "past_due" | "canceled";
        maxStudents?: number;
        maxCycles?: number;
    };
};

export type admin_role = {
    name: string;
    level: number;
    permissions: {
        manageUsers?: boolean;
        viewUsers?: boolean;
        manageSchools?: boolean;
        viewSchools?: boolean;
        manageClasses?: boolean;
        manageGrades?: boolean;
        manageSystem?: boolean;
        viewAnalytics?: boolean;
        manageSettings?: boolean;
        manageBilling?: boolean;
        manageContent?: boolean;
        viewSupportTickets?: boolean;
        manageSupportTickets?: boolean;
        apiAccess?: boolean;
        exportData?: boolean;
    };
    description?: string;
};

export type staff = {
    uid: string;
    email: string;
    schoolId: string;
    role: "directeur" | "directeur_pedagogique" | "secretaire" | "enseignant" | "enseignant_principal" | "comptable" | "bibliothecaire" | "surveillant" | "infirmier" | "personnel";
    firstName: string;
    lastName: string;
    hireDate: string;
    baseSalary: number;
    displayName?: string;
    photoURL?: string;
    adminRole?: string;
    phone?: string;
    matricule?: string;
    status?: "Actif" | "Inactif";
    subject?: string;
    classId?: string;
    situationMatrimoniale?: "Célibataire" | "Marié(e)" | "Divorcé(e)" | "Veuf(ve)";
    enfants?: number;
    categorie?: string;
    cnpsEmploye?: string;
    indemniteTransportImposable?: number;
    indemniteResponsabilite?: number;
    indemniteLogement?: number;
    indemniteSujetion?: number;
    indemniteCommunication?: number;
    indemniteRepresentation?: number;
    transportNonImposable?: number;
    banque?: string;
    numeroCompte?: string;
    CB?: string;
    CG?: string;
    Cle_RIB?: string;
    CNPS?: boolean;
    id?: string;
};

export interface UserProfile extends staff {
    permissions?: admin_role['permissions'];
}


export type student = {
    schoolId: string;
    firstName: string;
    lastName: string;
    matricule: string;
    status: "Actif" | "En attente" | "Radié";
    dateOfBirth: string;
    placeOfBirth: string;
    gender: "Masculin" | "Féminin";
    parent1FirstName: string;
    parent1LastName: string;
    parent1Contact: string;
    tuitionFee: number;
    amountDue: number;
    tuitionStatus: "Soldé" | "En retard" | "Partiel";
    inscriptionYear: number;
    photoUrl?: string;
    classId?: string;
    class?: string;
    cycle?: string;
    address?: string;
    parent2FirstName?: string;
    parent2LastName?: string;
    parent2Contact?: string;
    previousSchool?: string;
    discountAmount?: number;
    discountReason?: string;
    feedback?: string;
    createdAt?: string;
    id?: string;
    name?: string;
};

export type cycle = {
    schoolId: string;
    name: string;
    code: string;
    order: number;
    isActive?: boolean;
    description?: string;
    ageRange?: {
        min?: number;
        max?: number;
    };
    createdAt?: string;
    updatedAt?: string;
    id?: string;
    color?: string;
};

export type niveau = {
    schoolId: string;
    cycleId: string;
    name: string;
    code: string;
    order: number;
    ageMin: number;
    ageMax: number;
    capacity: number;
    color?: string;
    description?: string;
    createdAt?: string;
    updatedAt?: string;
    id?: string;
};

export type class_type = {
    schoolId: string;
    cycleId: string;
    niveauId: string;
    name: string;
    grade: string;
    code: string;
    academicYear: string;
    studentCount: number;
    maxStudents: number;
    status: "active" | "inactive" | "archived";
    isFull: boolean;
    createdBy: string;
    section?: string;
    mainTeacherId?: string;
    mainTeacherName?: string;
    teacherIds?: string[];
    coordinatorId?: string;
    schedule?: {
        startTime?: string;
        endTime?: string;
        days?: string[];
    };
    classroom?: string;
    building?: string;
    createdAt?: string;
    updatedAt?: string;
    id?: string;
    cycle?: string;
};

export type studentClassAssignment = {
    schoolId: string;
    studentId: string;
    classeId: string;
    academicYear: string;
    startDate: string;
    promotionType: "normal" | "redoublement" | "avancement";
    status: "active" | "transferred" | "graduated" | "withdrawn";
    createdBy: string;
    endDate?: string;
    previousClass?: string;
    notes?: string;
    createdAt?: string;
    id?: string;
};

export type timetableEntry = {
    schoolId: string;
    classId: string;
    teacherId: string;
    subject: string;
    day: "Lundi" | "Mardi" | "Mercredi" | "Jeudi" | "Vendredi" | "Samedi";
    startTime: string;
    endTime: string;
    classroom?: string;
    color?: string;
    id?: string;
};

export type gradeEntry = {
    subject: string;
    type: "Interrogation" | "Devoir";
    date: string;
    grade: number;
    coefficient: number;
    id?: string;
};

export type accountingTransaction = {
    schoolId: string;
    date: string;
    description: string;
    category: string;
    type: "Revenu" | "Dépense";
    amount: number;
    id?: string;
};

export type payment = {
    date: string;
    amount: number;
    description: string;
    accountingTransactionId: string;
    payerFirstName: string;
    payerLastName: string;
    method: "Espèces" | "Chèque" | "Virement Bancaire" | "Paiement Mobile";
    payerContact?: string;
    id?: string;
};

export type libraryBook = {
    schoolId: string;
    title: string;
    author: string;
    quantity: number;
    createdAt?: string;
    id?: string;
};

export type message = {
    schoolId: string;
    title: string;
    content: string;
    senderId: string;
    senderName: string;
    createdAt: string;
    recipients: {
        all?: boolean;
        teachers?: boolean;
        staff?: boolean;
        classes?: string[];
    };
    id?: string;
};

export type absence = {
    schoolId: string;
    studentId: string;
    studentName: string;
    classId: string;
    date: string;
    type: "Journée entière" | "Matin" | "Après-midi";
    justified: boolean;
    recordedBy: string;
    reason?: string;
    id?: string;
};

export type fee = {
    schoolId: string;
    grade: string;
    amount: string;
    installments: string;
    details?: string;
    id?: string;
};

export type subject = {
    schoolId: string;
    name: string;
    code?: string;
    color?: string;
    id?: string;
};

export type canteenMenu = {
    date: string;
    mealType: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    status: "draft" | "published" | "archived";
    categories: {
        name?: string;
        items?: {
            name?: string;
            description?: string;
            allergens?: string[];
            priceStudent?: number;
            priceStaff?: number;
            options?: string[];
        }[];
    }[];
    specialMenus?: {
        vegetarian?: {
            available?: boolean;
            mainCourse?: string;
        };
        halal?: {
            available?: boolean;
            mainCourse?: string;
        };
        allergies?: string[];
    };
    id?: string;
};

export type canteenReservation = {
    studentId: string;
    date: string;
    mealType: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    status: "pending" | "confirmed" | "cancelled" | "attended";
    paymentStatus: "unpaid" | "paid" | "partially_paid";
    price: number;
    menuChoice?: {
        entree?: string;
        mainCourse?: string;
        dessert?: string;
        option?: string;
    };
    specialRequirements?: string;
    paidAmount?: number;
    attendanceTime?: string;
    notes?: string;
    id?: string;
};

export type canteenSubscription = {
    studentId: string;
    type: "ponctuel" | "hebdomadaire" | "mensuel" | "trimestriel" | "annuel";
    startDate: string;
    endDate: string;
    price: number;
    status: "active" | "inactive" | "expired";
    daysOfWeek?: string[];
    mealType?: "petit_dejeuner" | "dejeuner" | "gouter" | "diner";
    autoRenew?: boolean;
    missedMeals?: number;
    remainingMeals?: number;
    id?: string;
};
