
export const DEMO_STUDENTS = [
    {
        id: 'std_001',
        firstName: 'Awa',
        lastName: 'Diop',
        matricule: 'AWD-2024-001',
        class: 'CM2-A',
        age: 10,
        status: 'Actif',
        tuitionStatus: 'Soldé',
        photoUrl: 'https://i.pravatar.cc/150?img=1',
    },
    {
        id: 'std_002',
        firstName: 'Moussa',
        lastName: 'Traoré',
        matricule: 'MTR-2024-002',
        class: '6ème-B',
        age: 11,
        status: 'Actif',
        tuitionStatus: 'Partiel',
        photoUrl: 'https://i.pravatar.cc/150?img=2',
    },
    {
        id: 'std_003',
        firstName: 'Fatou',
        lastName: 'Ndiaye',
        matricule: 'FND-2024-003',
        class: 'Terminale D',
        age: 17,
        status: 'Actif',
        tuitionStatus: 'En retard',
        photoUrl: 'https://i.pravatar.cc/150?img=3',
    },
    {
        id: 'std_004',
        firstName: 'Ibrahim',
        lastName: 'Koné',
        matricule: 'IKO-2024-004',
        class: 'CP1-A',
        age: 6,
        status: 'Actif',
        tuitionStatus: 'Soldé',
        photoUrl: 'https://i.pravatar.cc/150?img=4',
    },
    {
        id: 'std_005',
        firstName: 'Aïcha',
        lastName: 'Cissé',
        matricule: 'ACS-2024-005',
        class: '4ème-C',
        age: 13,
        status: 'Actif',
        tuitionStatus: 'Partiel',
        photoUrl: 'https://i.pravatar.cc/150?img=5',
    },
        {
        id: 'std_006',
        firstName: 'Sékou',
        lastName: 'Camara',
        matricule: 'SCA-2024-006',
        class: 'Seconde S',
        age: 15,
        status: 'En attente',
        tuitionStatus: 'Partiel',
        photoUrl: 'https://i.pravatar.cc/150?img=6',
    },
    {
        id: 'std_007',
        firstName: 'Mariam',
        lastName: 'Sow',
        matricule: 'MSW-2024-007',
        class: 'Première L',
        age: 16,
        status: 'Actif',
        tuitionStatus: 'Soldé',
        photoUrl: 'https://i.pravatar.cc/150?img=7',
    },
    {
        id: 'std_008',
        firstName: 'Demba',
        lastName: 'Fall',
        matricule: 'DFA-2024-008',
        class: 'CM1-B',
        age: 9,
        status: 'Radié',
        tuitionStatus: 'En retard',
        photoUrl: 'https://i.pravatar.cc/150?img=8',
    },
];
