export const allPermissions = {
    manageUsers: true,
    viewUsers: true,
    manageSchools: true,
    viewSchools: true,
    manageClasses: true,
    manageGrades: true,
    manageDiscipline: true,
    manageSystem: true,
    viewAnalytics: true,
    manageSettings: true,
    manageBilling: true,
    manageCommunication: true,
    manageSchedule: true,
    manageAttendance: true,
    manageLibrary: true,
    manageCantine: true,
    manageTransport: true,
    manageInternat: true,
    manageInventory: true,
    manageRooms: true,
    manageActivities: true,
    manageMedical: true,
    viewSupportTickets: true,
    manageSupportTickets: true,
    apiAccess: true,
    exportData: true,
};
