
export const allPermissions = {
    manageUsers: true,
    viewUsers: true,
    manageSchools: true,
    viewSchools: true,
    manageClasses: true,
    manageGrades: true,
    viewGrades: true,
    manageDiscipline: true,
    manageSystem: true,
    viewAnalytics: true,
    manageSettings: true,
    manageBilling: true,
    manageCommunication: true,
    manageSchedule: true,
    manageAttendance: true,
    manageLibrary: true,
    manageCantine: true,
    manageTransport: true,
    manageInternat: true,
    manageInventory: true,
    manageRooms: true,
    manageActivities: true,
    manageMedical: true,
    viewSupportTickets: true,
    manageSupportTickets: true,
    apiAccess: true,
    exportData: true,
};

export const allPermissionsList = [
    { id: 'manageUsers', label: 'Gérer Utilisateurs', desc: 'Créer, modifier, supprimer élèves et personnel.' },
    { id: 'viewUsers', label: 'Voir Utilisateurs', desc: 'Consulter les listes et profils.' },
    { id: 'manageClasses', label: 'Gérer Classes', desc: 'Créer, modifier la structure scolaire.' },
    { id: 'manageGrades', label: 'Gérer Notes', desc: 'Saisir et modifier les notes des élèves.' },
    { id: 'viewGrades', label: 'Voir Notes', desc: 'Consulter les notes et bulletins des élèves.'},
    { id: 'manageDiscipline', label: 'Gérer Discipline', desc: "Suivre et gérer les incidents disciplinaires."},
    { id: 'manageBilling', label: 'Gérer Facturation', desc: 'Gérer les paiements, frais et comptabilité.' },
    { id: 'manageCommunication', label: 'Gérer Communication', desc: 'Envoyer des messages à la communauté.' },
    { id: 'manageSchedule', label: 'Gérer Emploi du temps', desc: 'Modifier les emplois du temps.' },
    { id: 'manageAttendance', label: 'Gérer Absences', desc: 'Enregistrer les absences des élèves.' },
    { id: 'manageLibrary', label: 'Gérer Bibliothèque', desc: 'Ajouter/supprimer des livres.' },
    { id: 'manageCantine', label: 'Gérer Cantine', desc: 'Gérer les menus et réservations.' },
    { id: 'manageTransport', label: 'Gérer Transport', desc: 'Gérer la flotte, les lignes et abonnements.' },
    { id: 'manageInternat', label: 'Gérer Internat', desc: 'Gérer les bâtiments, chambres et occupants.' },
    { id: 'manageInventory', label: 'Gérer Inventaire', desc: 'Gérer le matériel de l\'école.' },
    { id: 'manageRooms', label: 'Gérer Salles', desc: 'Créer et modifier les salles.' },
    { id: 'manageActivities', label: 'Gérer Activités', desc: 'Gérer les activités parascolaires.' },
    { id: 'manageMedical', label: 'Gérer Dossiers Médicaux', desc: 'Accès et modification des dossiers de santé.' },
    { id: 'manageSettings', label: 'Gérer Paramètres École', desc: 'Modifier les paramètres de l\'établissement.' },
    { id: 'viewAnalytics', label: 'Voir Statistiques', desc: 'Accéder aux tableaux de bord analytiques.'},
    { id: 'viewSupportTickets', label: 'Voir Tickets Support', desc: 'Consulter les tickets de support.' },
    { id: 'manageSupportTickets', label: 'Gérer Tickets Support', desc: 'Répondre et fermer les tickets.' },
    { id: 'exportData', label: 'Exporter Données', desc: 'Permet d\'exporter les données de l\'école.' },
] as const;

export type PermissionId = typeof allPermissionsList[number]['id'];
